### ISSUE TITLE
UnboundLocalError: local variable 'value' referenced before assignment

### ISSUE THREAD

**Issue by Borthralla** [ome/omero-metadata#21]
I tried running `bin/omero metadata populate --file annotations.csv Project:201` and got the followong output: 
```
Using session for root@localhost:4064. Idle timeout: 10 min. Current group: system
INFO:omero.util.populate_metadata:Adding dataset:505 image:40456
INFO:omero.util.populate_metadata:Adding dataset:505 image:40455
INFO:omero.util.populate_metadata:Adding dataset:505 image:40454
INFO:omero.util.populate_metadata:Adding dataset:505 image:40453
INFO:omero.util.populate_metadata:Adding dataset:505 image:40452
INFO:omero.util.populate_metadata:Adding dataset:505 image:40451
INFO:omero.util.populate_metadata:Adding dataset:505 image:40450
INFO:omero.util.populate_metadata:Adding dataset:505 image:40449
INFO:omero.util.populate_metadata:Adding dataset:505 image:40448
INFO:omero.util.populate_metadata:Adding dataset:505 image:40447
INFO:omero.util.populate_metadata:Created new table OriginalFile:54420
Traceback (most recent call last):
  File "bin/omero", line 130, in <module>
    rv = omero.cli.argv()
  File "/home/omero/OMERO.server-5.4.9-ice36-b101/lib/python/omero/cli.py", line 1620, in argv
    cli.invoke(args[1:])
  File "/home/omero/OMERO.server-5.4.9-ice36-b101/lib/python/omero/cli.py", line 1095, in invoke
    stop = self.onecmd(line, previous_args)
  File "/home/omero/OMERO.server-5.4.9-ice36-b101/lib/python/omero/cli.py", line 1172, in onecmd
    self.execute(line, previous_args)
  File "/home/omero/OMERO.server-5.4.9-ice36-b101/lib/python/omero/cli.py", line 1254, in execute
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/omero_cli_metadata.py", line 491, in populate
    ctx.parse()
  File "/usr/local/lib/python2.7/dist-packages/populate_metadata.py", line 993, in parse
    return self.parse_from_handle_stream(data)
  File "/usr/local/lib/python2.7/dist-packages/populate_metadata.py", line 963, in parse_from_handle_stream
    self.populate_from_reader(reader, self.filter_function, table, 1000)
  File "/usr/local/lib/python2.7/dist-packages/populate_metadata.py", line 1070, in populate_from_reader
    self.populate_row(row)
  File "/usr/local/lib/python2.7/dist-packages/populate_metadata.py", line 1043, in populate_row
    if value.__class__ is not Skip:
UnboundLocalError: local variable 'value' referenced before assignment
```
The annotation.csv file looked like this: 
```
flavor,num_layers,color,shape,price,Image Name,Dataset Name
strawberry,1,white,circle,5,cake1.jpg,cake
strawberry,2,white,circle,50,cake2.jpg,cake
strawberry,3,white,circle,50,cake3.jpg,cake
strawberry,4,white,circle,50,cake4.jpg,cake
strawberry,5,white,circle,50,cake5.jpg,cake
strawberry,5,white,circle,50,cake6.jpg,cake
strawberry,5,white,circle,50,cake7.jpg,cake
strawberry,5,white,circle,5000000,cake8.jpg,cake
strawberry,5,white,circle,50,cake9.jpg,cake
strawberry,5,white,circle,50,cake10.jpg,cake
```

Any idea about what happened?

**Comment by Borthralla** [comment]
I figured out what happened. The annotations.csv had a trailing newline at the end, which caused one of the rows to have length 0, meaning the loop which set the value variable was never iterated through. I just needed to delete the trailing newline. 
It probably should just throw an error saying "blank row in csv" or something, right?

**Comment by sbesson** [comment]
@Borthralla thanks for reporting the issue and also troubleshooting the cause. I agree that the plugin might want to handle empty rows  more gracefully. In terms of expected behavior, I can see the two following options when detecting empty rows:

1. throw an error with an informative message
2. simply skipping an empty row with a warning

The second solution is probably the best in terms of user experience but I have not thought is through completely. Would be any downside with pruning empty rows from a CSV annotation file?

**Comment by Borthralla** [comment]
Maybe if there is a blank row in the middle of the csv, then that may indicate the file was incorrectly formatted or corrupted, in which case an error may be appropriate. Trailing newlines are probably fine though, is there an easy way to trim off trailing newlines?

**Comment by sbesson** [comment]
@Borthralla: I think the following lines could include a nullity check on the value of `row` to catch csv files with empty lines and enable the desired behavior:

https://github.com/ome/omero-metadata/blob/e63945d4b3b81ae00708d44189de73832cde17de/src/populate_metadata.py#L1003-L1005

Since `reader` is an iterator extra logic will be needed to differentiate trailing newlines from empty lines in the middle of the file.

**Comment by dominikl** [comment]
Ran into this issue as well. Initially I thought a linebreak at the end of the last entry causes it. But that's not the case, works fine. You really need a empty line with a linebreak at the end of the file. I think it's ok to fail in that case - also with empty lines somewhere inbetween, as these are not valid csv files strictly speaking. But the error message is indeed very cryptic.
