### ISSUE TITLE
populate_metadata module is not under omero*

### ISSUE THREAD

**Issue by manics** [ome/omero-metadata#22]
Expected: The `populate_metadata` module should be under `omero*`, e.g. `import omero.populate_metadata` or `import omero_metadata.populate_metadata`.

Actual: It's at the top level, `import populate_metadata`

Suggestion: Use the same layout in [omero-upload](https://github.com/ome/omero-upload/tree/v0.2.0/src/omero_upload) where [`omero_upload/__init__.py`](https://github.com/ome/omero-upload/blob/v0.2.0/src/omero_upload/__init__.py) contains the public API methods

**Comment by sbesson** [comment]
I assume this is now fixed by `omero-metadata 0.4.0` and more specifically https://github.com/ome/omero-metadata/pull/19 which moves all modules outside the root namespace into `omero_metadata.*`
