### ISSUE TITLE
populate metadata should strip CSV values

### ISSUE THREAD

**Issue by will-moore** [ome/omero-metadata#24]
CSV files may contain ```values, with, whitespace``` which should be ignored
by ```value.strip()```. E.g. if a CSV file has been edited in a text-editor etc.

**Comment by sbesson** [comment]
If it's only the initial whitespace after the delimiter, I would think setting [skipinitialspace](https://docs.python.org/2/library/csv.html#csv.Dialect.skipinitialspace) to `True` in all `csv.reader()` invocations might suffice.

I am unsure whether there are concrete use cases where we want to preserve leading whitespaces for string values. If this is the case, this behavior should be made configurable.

**Comment by manics** [comment]
I'm not sure about this. It's definitely convenient in this case, but it changes the script from one for transforming CSVs to one that actively does data cleaning and wrangling, and means the raw data may not exactly match that in the bulk annotations. For example in the IDR the CSVs in https://github.com/IDR/idr-metadata are the original data, and part of the import process is to clean them up if necessary.

How about an _optional_ `validate`/`lint` command/flag that warns or errors if common errors are detected?

**Comment by will-moore** [comment]
@sbesson Thanks for the ```skipinitialspace``` pointer. I thought there should be something like that available but I didn't spot that.
I agree, it seems reasonable to add configuration for this once we know of any concrete use cases.
@manics I wouldn't see this as "cleaning", it's really just allowing your csv file to have spaces, which some do.
But I'm not sure we need this for any particular Training workflows cc @pwalczysko other than ones I was trying?

**Comment by pwalczysko** [comment]
I thnik the main method for creating CSV files for our "basic" users would be to go via Excel. These CSVs are created "correctly". no whitespaces.

Maybe this is not worth the effort then ?

**Comment by manics** [comment]
@will-moore Anything that involves manipulation of the raw data into a form in which it can be parsed counts as cleaning. In this example it's fairly innocuous, but in other situations people may be using a CSV as input to multiple pipelines. not just OMERO. Applications which clean data in different ways will lead to results which don't match as expected so we need to be clear if we're automatically making corrections to data.
