### ISSUE TITLE
Bug in Exception Message for duplicate Image names

### ISSUE THREAD

**Issue by JensWendt** [ome/omero-metadata#68]
Hello,

I just wanted to make you aware of a small bug in line 803 of `populate.py`.
While playing around with the script `populate metadata` I had a case where - unknowingly - two images were named the same.
This problem is caught in the if clause : `if iname in self.images_by_name`
but in the following raised Exception message: 
                  `"Image named %s(id=%d) present. (id=%s) % (
                    iname, self.images_by_name[iname], iid`
the second format `%d` expects the image ID but gets an `ImageI ` variable. 
This is easily corrected by adding `self.images_by_name[iname]`**.id.val** 
I tried it out and now it gives the correct error message.

**Comment by will-moore** [comment]
I came across this bug while working on https://github.com/ome/omero-metadata/pull/62 so I have included a fix in that PR.

**Comment by JensWendt** [comment]
okay, perfect. wasn't aware. thank you
